## Modules

In [17]:
import os
import numpy as np

In [18]:
# make a list and cast it as an array
my_list = [1, 2, 3, 4]
arr = np.array(my_list)
arr

array([1, 2, 3, 4])

In [19]:
# make a matrix using my list
my_list2 = list(range(10))
type(my_list2)
my_list2
my_list2 = np.array(my_list2)
my_list_split = np.split(my_list2, 2)
np.array(my_list_split)




array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# Generating arrays faster

np.arange(0, 10) # similar to range used above
np.arange(0, 11, 2) # step size if I want only even numbers. Step size is the third parm
x = np.arange(0, 10) # similar to range used above
x_split = np.split(x, 2)
np.array(x_split)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Identity Matrices 

Useful when dealing with linear algebro problems. It's a 2D square matrix. Rows and columns equal, and 1s are all accross the diagonal

In [21]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## How to make random numbers

In [22]:
one_d = np.random.rand(5)
one_d
two_d = np.random.rand(5, 5)
two_d

array([[0.77720718, 0.85485033, 0.73583897, 0.4819946 , 0.83074832],
       [0.06157028, 0.47971289, 0.59542031, 0.71884649, 0.70494784],
       [0.4571022 , 0.35337797, 0.24052087, 0.76910747, 0.97161469],
       [0.58371349, 0.58619097, 0.8047701 , 0.89398582, 0.91943394],
       [0.34038931, 0.66371908, 0.67168824, 0.87553133, 0.45601897]])

In [23]:
# Random numbers from a standard dist

one_d = np.random.randn(4)
one_d
two_d = np.random.randn(4, 4)
two_d

array([[-0.42560533, -0.32544983,  0.54416451, -0.72792818],
       [ 1.48423102,  0.47196519,  0.91016994,  0.81777644],
       [ 1.03086689,  1.04005963,  2.12035178,  0.13957075],
       [-1.04081961, -0.30320956,  1.11643372,  1.2815519 ]])

In [24]:
# Random integers from a low to a high number

rand = np.random.randint(4, 51, 10)
rand


array([36, 29, 27, 28, 17, 29, 14, 24, 11, 20])

## Random Practice

In [25]:
rand_array = np.arange(25)
rand_Mat = np.random.randint(4, 51, 10)


In [26]:
rand_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
rand_Mat

array([24, 20, 20,  9, 28, 33, 23, 39, 37,  8])

In [28]:
rand_array.reshape(5,5) # If you wanted to reshape your array. Although why you'd want that I don't know.
# Reshaping numpy array is useful to convert array into a shape that is expected by a machine learning/deep learning model. 
# For example, most neural networks expect input values to be in a single column array.
rand_array.max() # finds max value
rand_array.min() # finds min value

# argmin & argmax shows the index value of the min or max in the array.

0

## Operations

In [29]:
arr2 = np.arange(0, 13)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
# Addition

arr2 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [31]:
# Subtraction

arr2 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# Multiplication

arr2 * arr2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [33]:
# scalar operation. Scalar means single number

arr2 + 100


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112])