In [1]:
import numpy as np

## Indexing a Matrix

In [4]:
matrix = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [5]:
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
# If I wanted to grab 5 from matrix
matrix[0] [0] # row, column
# If I wanted the first row of matrix
matrix[1]
# If I wanted the first column of matrix?


10

In [15]:
# comma notation
matrix[0,1]
matrix[1]

array([20, 25, 30])

In [16]:
# Navigating how much of the array you want requires slice notation.
# If I want the top 4 elements from the right:
matrix[:2, 1:]

array([[10, 15],
       [25, 30]])

In [20]:
# I want just middle column
matrix[:3]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

## The above is pretty important just in terms of slice notation and using brackets to navigate. 

## Important: Conditional Selection

In [21]:
arr = np.arange(1, 11)

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# applying a conditional to your array.
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
# Conditonal selection
arr[arr < 4]

array([1, 2, 3])

In [26]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [28]:
# Indexing Practice
arr_2d[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [35, 36, 37, 38, 39],
       [45, 46, 47, 48, 49]])