In [1]:
import numpy as np

In [4]:
arr = np.arange(0, 13)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## How to pick something out of array

In [6]:
arr[9]

9

In [7]:
arr[0: 7] # everything between two points

array([0, 1, 2, 3, 4, 5, 6])

In [9]:
arr[:7] # everything to the defined point

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
arr[5:] # everything from and after defined point

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
# You can set values in an array
arr[0:6] = 100

In [12]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12])

In [13]:
# Reset
arr = np.arange(0, 13)

In [15]:
# Slice/subset elements of the array into its own array
slice_of_arr = arr[0:6]
slice_of_arr[:] #pulls all of the array

array([0, 1, 2, 3, 4, 5])

In [17]:
# If you change values of the slice, what happens to original?
slice_of_arr[:] = 50
slice_of_arr
arr

# slice_of_arr is not a copy of the original array. Therefore changes you make, change the original.

array([50, 50, 50, 50, 50, 50,  6,  7,  8,  9, 10, 11, 12])

In [18]:
# Reset
arr = np.arange(0, 13)

In [21]:
## If you want to copy original and change in isolation, do the following:

arr_copy = arr.copy()
slice2 = arr_copy[0:5]
slice2[:] = 50
slice2
arr_copy
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])